#ifndef DS_H
#define DS_H

#include <algorithm>
#include <cmath>
#include <deque>
#include <limits>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

/*
 * ds.h
 * Data structures for:
 * Step 1: Build Clock Tree Model and Timing Path Model
 *
 * This header focuses on:
 * 1. Buffer library representation
 * 2. Clock tree representation
 * 3. FF table
 * 4. Timing path table
 * 5. Basic helper functions for slack / arrival time / critical path graph
 */

namespace skew {

static constexpr int INVALID_ID = -1;
static constexpr double INF = std::numeric_limits<double>::infinity();

enum class NodeType {
    ROOT,
    BUFFER,
    FF
};

enum class Corner {
    SS,
    FF
};

enum class ConstraintKind {
    SETUP,
    HOLD
};

enum class OperationType {
    NONE,
    RESIZE_BUFFER,
    INSERT_BUFFER
};

/* ============================================================
 * 1. Buffer Library
 * ============================================================
 */

struct CellLib {
    std::string name;

    double width = 0.0;
    double height = 0.0;
    double area = 0.0;

    // index = fanout - 1
    std::vector<double> ssDelay;
    std::vector<double> ffDelay;

    void updateArea() {
        area = width * height;
    }

    int maxFanout() const {
        return static_cast<int>(std::min(ssDelay.size(), ffDelay.size()));
    }

    bool isLegalFanout(int fanout) const {
        return fanout >= 1 && fanout <= maxFanout();
    }

    double getDelay(Corner corner, int fanout) const {
        if (!isLegalFanout(fanout)) {
            throw std::out_of_range(
                "Illegal fanout for cell " + name +
                ", fanout = " + std::to_string(fanout)
            );
        }

        if (corner == Corner::SS) {
            return ssDelay[fanout - 1];
        } else {
            return ffDelay[fanout - 1];
        }
    }

    double getDelaySS(int fanout) const {
        return getDelay(Corner::SS, fanout);
    }

    double getDelayFF(int fanout) const {
        return getDelay(Corner::FF, fanout);
    }
};

/* ============================================================
 * 2. Clock Tree Node
 * ============================================================
 */

struct TreeNode {
    int id = INVALID_ID;
    std::string name;

    NodeType type = NodeType::BUFFER;

    // Example:
    // BUFFER: REALBUF_X8
    // FF    : FIFO
    std::string instType;

    int parent = INVALID_ID;
    std::vector<int> children;

    int level = 0;

    // Valid only if type == BUFFER
    int cellId = INVALID_ID;

    // Valid only if type == FF
    int ffId = INVALID_ID;
    bool isSink = false;

    // For generated buffers
    bool isNewBuffer = false;

    // Clock arrival time from root to this node
    double clkSS = 0.0;
    double clkFF = 0.0;

    // Euler interval over FF leaves
    // Used to check whether a FF is inside a subtree quickly
    int tin = -1;
    int tout = -1;

    int fanout() const {
        return static_cast<int>(children.size());
    }

    bool isRoot() const {
        return type == NodeType::ROOT;
    }

    bool isBuffer() const {
        return type == NodeType::BUFFER;
    }

    bool isFF() const {
        return type == NodeType::FF;
    }
};

/* ============================================================
 * 3. Flip-Flop Info
 * ============================================================
 */

struct FFInfo {
    int ffId = INVALID_ID;
    std::string name;

    // Corresponding node in clock tree
    int treeNodeId = INVALID_ID;

    // Current clock arrival time
    double clkSS = 0.0;
    double clkFF = 0.0;

    // Target values generated by Step 2
    double targetArrivalSS = 0.0;
    double targetArrivalFF = 0.0;

    double targetShiftSS = 0.0;
    double targetShiftFF = 0.0;

    // Euler order position
    int tin = -1;

    // Timing paths connected to this FF
    std::vector<int> launchPaths;
    std::vector<int> capturePaths;
};

/* ============================================================
 * 4. Timing Path
 * ============================================================
 */

struct TimingPath {
    int id = INVALID_ID;
    std::string name;

    int launchFF = INVALID_ID;
    int captureFF = INVALID_ID;

    double ssDataDelay = 0.0;
    double ffDataDelay = 0.0;

    bool hasSS = false;
    bool hasFF = false;

    double setupSlack = 0.0;
    double holdSlack = 0.0;

    bool setupCritical = false;
    bool holdCritical = false;

    bool valid() const {
        return launchFF != INVALID_ID &&
               captureFF != INVALID_ID &&
               hasSS &&
               hasFF;
    }
};

/* ============================================================
 * 5. Constraint Edge for SPFA / Bellman-Ford
 *
 * Meaning:
 *     x[to] <= x[from] + weight
 * ============================================================
 */

struct ConstraintEdge {
    int from = INVALID_ID;
    int to = INVALID_ID;
    double weight = 0.0;

    int pathId = INVALID_ID;
    ConstraintKind kind = ConstraintKind::SETUP;
};

/* ============================================================
 * 6. Operation / DP State
 *    These are mainly for Step 3, but placed here so every
 *    module can share the same structure.
 * ============================================================
 */

struct Operation {
    OperationType type = OperationType::NONE;

    // For resize
    int nodeId = INVALID_ID;
    int oldCellId = INVALID_ID;
    int newCellId = INVALID_ID;

    // For insert buffer
    int insertParentId = INVALID_ID;
    int insertChildId = INVALID_ID;
    std::string newBufferName;

    double areaDelta = 0.0;
    double ssDelayDelta = 0.0;
    double ffDelayDelta = 0.0;
};

struct DPState {
    double ssDelayDelta = 0.0;
    double ffDelayDelta = 0.0;
    double areaDelta = 0.0;

    double estimatedGain = 0.0;

    std::vector<Operation> operations;
};

/* ============================================================
 * 7. Score Summary
 * ============================================================
 */

struct ScoreSummary {
    double tnsSS = 0.0;
    double wnsSS = 0.0;

    double tnsFF = 0.0;
    double wnsFF = 0.0;

    double totalArea = 0.0;
};

/* ============================================================
 * 8. Whole Design Database
 * ============================================================
 */

struct DesignDB {
    std::vector<CellLib> libs;
    std::vector<TreeNode> tree;
    std::vector<FFInfo> ffs;
    std::vector<TimingPath> paths;

    // SPFA graph for Step 2
    std::vector<std::vector<ConstraintEdge>> spfaAdj;

    std::unordered_map<std::string, int> cellNameToId;
    std::unordered_map<std::string, int> nodeNameToId;
    std::unordered_map<std::string, int> ffNameToId;
    std::unordered_map<std::string, int> pathNameToId;

    int rootId = INVALID_ID;

    double clockPeriod = 0.0;
    double originalArea = 0.0;

    /* ----------------------------
     * Basic timing constants
     * ----------------------------
     */

    double setupTime() const {
        return 0.08 * clockPeriod;
    }

    double holdTime() const {
        return 0.05 * clockPeriod;
    }

    /* ----------------------------
     * Library helper
     * ----------------------------
     */

    int addCell(CellLib cell) {
        if (cell.name.empty()) {
            throw std::runtime_error("Cell name cannot be empty.");
        }

        if (cell.area <= 0.0) {
            cell.updateArea();
        }

        int id = static_cast<int>(libs.size());
        libs.push_back(cell);
        cellNameToId[cell.name] = id;
        return id;
    }

    int getCellId(const std::string& name) const {
        auto it = cellNameToId.find(name);
        if (it == cellNameToId.end()) {
            return INVALID_ID;
        }
        return it->second;
    }

    const CellLib& getCell(int cellId) const {
        if (cellId < 0 || cellId >= static_cast<int>(libs.size())) {
            throw std::out_of_range("Invalid cellId.");
        }
        return libs[cellId];
    }

    CellLib& getCell(int cellId) {
        if (cellId < 0 || cellId >= static_cast<int>(libs.size())) {
            throw std::out_of_range("Invalid cellId.");
        }
        return libs[cellId];
    }

    /* ----------------------------
     * Clock tree helper
     * ----------------------------
     */

    int addTreeNode(
        const std::string& name,
        NodeType type,
        const std::string& instType = "",
        int level = 0,
        int cellId = INVALID_ID,
        bool isSink = false
    ) {
        if (name.empty()) {
            throw std::runtime_error("Tree node name cannot be empty.");
        }

        if (nodeNameToId.count(name)) {
            throw std::runtime_error("Duplicated tree node name: " + name);
        }

        TreeNode node;
        node.id = static_cast<int>(tree.size());
        node.name = name;
        node.type = type;
        node.instType = instType;
        node.level = level;
        node.cellId = cellId;
        node.isSink = isSink;

        // If this is a buffer and cellId is not given,
        // try to find it by instType.
        if (type == NodeType::BUFFER && node.cellId == INVALID_ID) {
            node.cellId = getCellId(instType);
        }

        int id = node.id;
        tree.push_back(node);
        nodeNameToId[name] = id;

        if (type == NodeType::ROOT) {
            rootId = id;
        }

        if (type == NodeType::FF) {
            registerFFNode(id);
        }

        return id;
    }

    void setParent(int childId, int parentId) {
        if (!validTreeNode(childId) || !validTreeNode(parentId)) {
            throw std::out_of_range("Invalid parent or child id.");
        }

        tree[childId].parent = parentId;
        tree[parentId].children.push_back(childId);
    }

    bool validTreeNode(int nodeId) const {
        return nodeId >= 0 && nodeId < static_cast<int>(tree.size());
    }

    int getTreeNodeId(const std::string& name) const {
        auto it = nodeNameToId.find(name);
        if (it == nodeNameToId.end()) {
            return INVALID_ID;
        }
        return it->second;
    }

    double getNodeArea(int nodeId) const {
        if (!validTreeNode(nodeId)) {
            throw std::out_of_range("Invalid nodeId.");
        }

        const TreeNode& node = tree[nodeId];

        if (!node.isBuffer()) {
            return 0.0;
        }

        if (node.cellId == INVALID_ID) {
            return 0.0;
        }

        return libs[node.cellId].area;
    }

    double computeTotalBufferArea() const {
        double total = 0.0;

        for (const auto& node : tree) {
            if (node.isBuffer()) {
                total += getNodeArea(node.id);
            }
        }

        return total;
    }

    void updateOriginalArea() {
        originalArea = computeTotalBufferArea();
    }

    /* ----------------------------
     * FF helper
     * ----------------------------
     */

    int registerFFNode(int treeNodeId) {
        if (!validTreeNode(treeNodeId)) {
            throw std::out_of_range("Invalid FF tree node id.");
        }

        TreeNode& node = tree[treeNodeId];

        if (!node.isFF()) {
            throw std::runtime_error("registerFFNode called on non-FF node.");
        }

        if (ffNameToId.count(node.name)) {
            return ffNameToId[node.name];
        }

        FFInfo ff;
        ff.ffId = static_cast<int>(ffs.size());
        ff.name = node.name;
        ff.treeNodeId = treeNodeId;

        int ffId = ff.ffId;
        ffs.push_back(ff);

        node.ffId = ffId;
        ffNameToId[node.name] = ffId;

        return ffId;
    }

    int getFFId(const std::string& name) const {
        auto it = ffNameToId.find(name);
        if (it == ffNameToId.end()) {
            return INVALID_ID;
        }
        return it->second;
    }

    bool validFF(int ffId) const {
        return ffId >= 0 && ffId < static_cast<int>(ffs.size());
    }

    /* ----------------------------
     * Clock arrival time
     * ----------------------------
     */

    void computeClockArrival() {
        if (!validTreeNode(rootId)) {
            throw std::runtime_error("Root is not set.");
        }

        computeClockArrivalDFS(rootId, 0.0, 0.0);
    }

    void computeClockArrivalDFS(int nodeId, double curSS, double curFF) {
        TreeNode& node = tree[nodeId];

        if (node.isBuffer()) {
            if (node.cellId == INVALID_ID) {
                throw std::runtime_error("Buffer without valid cellId: " + node.name);
            }

            int fo = node.fanout();
            const CellLib& cell = libs[node.cellId];

            curSS += cell.getDelaySS(fo);
            curFF += cell.getDelayFF(fo);
        }

        node.clkSS = curSS;
        node.clkFF = curFF;

        if (node.isFF()) {
            int fid = node.ffId;

            if (validFF(fid)) {
                ffs[fid].clkSS = curSS;
                ffs[fid].clkFF = curFF;
            }
        }

        for (int child : node.children) {
            computeClockArrivalDFS(child, curSS, curFF);
        }
    }

    /* ----------------------------
     * Euler Tour
     * Only FF nodes consume timer.
     * A subtree corresponds to a continuous FF interval.
     * ----------------------------
     */

    void buildEulerTour() {
        if (!validTreeNode(rootId)) {
            throw std::runtime_error("Root is not set.");
        }

        int timer = 0;
        buildEulerDFS(rootId, timer);
    }

    void buildEulerDFS(int nodeId, int& timer) {
        TreeNode& node = tree[nodeId];

        node.tin = timer;

        if (node.isFF()) {
            int fid = node.ffId;

            if (validFF(fid)) {
                ffs[fid].tin = timer;
            }

            timer++;
        }

        for (int child : node.children) {
            buildEulerDFS(child, timer);
        }

        node.tout = timer;
    }

    bool isFFInSubtree(int subtreeRootNodeId, int ffId) const {
        if (!validTreeNode(subtreeRootNodeId) || !validFF(ffId)) {
            return false;
        }

        int ffTreeNodeId = ffs[ffId].treeNodeId;

        if (!validTreeNode(ffTreeNodeId)) {
            return false;
        }

        const TreeNode& root = tree[subtreeRootNodeId];
        const TreeNode& ffNode = tree[ffTreeNodeId];

        return root.tin <= ffNode.tin && ffNode.tin < root.tout;
    }

    /* ----------------------------
     * Timing path helper
     * ----------------------------
     */

    int getOrCreatePath(
        const std::string& pathName,
        const std::string& launchFFName,
        const std::string& captureFFName
    ) {
        int launchId = getFFId(launchFFName);
        int captureId = getFFId(captureFFName);

        if (launchId == INVALID_ID) {
            throw std::runtime_error("Unknown launch FF: " + launchFFName);
        }

        if (captureId == INVALID_ID) {
            throw std::runtime_error("Unknown capture FF: " + captureFFName);
        }

        auto it = pathNameToId.find(pathName);

        if (it != pathNameToId.end()) {
            int pid = it->second;

            if (paths[pid].launchFF != launchId ||
                paths[pid].captureFF != captureId) {
                throw std::runtime_error("Path name conflict: " + pathName);
            }

            return pid;
        }

        TimingPath path;
        path.id = static_cast<int>(paths.size());
        path.name = pathName;
        path.launchFF = launchId;
        path.captureFF = captureId;

        int pid = path.id;
        paths.push_back(path);
        pathNameToId[pathName] = pid;

        return pid;
    }

    int setPathSSDelay(
        const std::string& pathName,
        const std::string& launchFFName,
        const std::string& captureFFName,
        double delay
    ) {
        int pid = getOrCreatePath(pathName, launchFFName, captureFFName);
        paths[pid].ssDataDelay = delay;
        paths[pid].hasSS = true;
        return pid;
    }

    int setPathFFDelay(
        const std::string& pathName,
        const std::string& launchFFName,
        const std::string& captureFFName,
        double delay
    ) {
        int pid = getOrCreatePath(pathName, launchFFName, captureFFName);
        paths[pid].ffDataDelay = delay;
        paths[pid].hasFF = true;
        return pid;
    }

    void rebuildPathIndex() {
        pathNameToId.clear();

        for (auto& ff : ffs) {
            ff.launchPaths.clear();
            ff.capturePaths.clear();
        }

        for (int i = 0; i < static_cast<int>(paths.size()); ++i) {
            paths[i].id = i;
            pathNameToId[paths[i].name] = i;

            int launch = paths[i].launchFF;
            int capture = paths[i].captureFF;

            if (validFF(launch)) {
                ffs[launch].launchPaths.push_back(i);
            }

            if (validFF(capture)) {
                ffs[capture].capturePaths.push_back(i);
            }
        }
    }

    /* ----------------------------
     * Slack calculation
     * ----------------------------
     */

    void computePathSlack(TimingPath& path) const {
        if (!path.valid()) {
            throw std::runtime_error("Invalid timing path: " + path.name);
        }

        const FFInfo& launch = ffs[path.launchFF];
        const FFInfo& capture = ffs[path.captureFF];

        double skewSS = capture.clkSS - launch.clkSS;
        double skewFF = capture.clkFF - launch.clkFF;

        path.setupSlack =
            clockPeriod - setupTime() - path.ssDataDelay + skewSS;

        path.holdSlack =
            path.ffDataDelay - holdTime() - skewFF;
    }

    void computeAllSlacks() {
        for (auto& path : paths) {
            computePathSlack(path);
        }
    }

    void markCriticalPaths(double thresholdRatio = 0.03) {
        double threshold = thresholdRatio * clockPeriod;

        for (auto& path : paths) {
            path.setupCritical = path.setupSlack < threshold;
            path.holdCritical = path.holdSlack < threshold;
        }
    }

    /* ----------------------------
     * SPFA constraint graph builder
     *
     * setup:
     *     x_capture - x_launch >= SS_data_delay + Tsetup - Tclk
     * =>  x_launch - x_capture <= -(SS_data_delay + Tsetup - Tclk)
     * edge:
     *     capture -> launch
     *
     * hold:
     *     x_capture - x_launch <= FF_data_delay - Thold
     * edge:
     *     launch -> capture
     * ----------------------------
     */

    void clearSPFAGraph() {
        spfaAdj.assign(ffs.size(), std::vector<ConstraintEdge>());
    }

    void addConstraintEdge(
        int from,
        int to,
        double weight,
        int pathId,
        ConstraintKind kind
    ) {
        if (!validFF(from) || !validFF(to)) {
            throw std::out_of_range("Invalid FF id in constraint edge.");
        }

        ConstraintEdge edge;
        edge.from = from;
        edge.to = to;
        edge.weight = weight;
        edge.pathId = pathId;
        edge.kind = kind;

        spfaAdj[from].push_back(edge);
    }

    void buildCriticalConstraintGraph() {
        clearSPFAGraph();

        for (const auto& path : paths) {
            if (!path.valid()) {
                continue;
            }

            int launch = path.launchFF;
            int capture = path.captureFF;

            if (path.setupCritical) {
                double rhs = path.ssDataDelay + setupTime() - clockPeriod;
                double weight = -rhs;

                addConstraintEdge(
                    capture,
                    launch,
                    weight,
                    path.id,
                    ConstraintKind::SETUP
                );
            }

            if (path.holdCritical) {
                double weight = path.ffDataDelay - holdTime();

                addConstraintEdge(
                    launch,
                    capture,
                    weight,
                    path.id,
                    ConstraintKind::HOLD
                );
            }
        }
    }

    /* ----------------------------
     * Target helper
     * ----------------------------
     */

    void clearTargets() {
        for (auto& ff : ffs) {
            ff.targetArrivalSS = ff.clkSS;
            ff.targetArrivalFF = ff.clkFF;
            ff.targetShiftSS = 0.0;
            ff.targetShiftFF = 0.0;
        }
    }

    /* ----------------------------
     * Initialization after parsing
     *
     * Suggested call order after all input files are parsed:
     *
     *     db.computeClockArrival();
     *     db.buildEulerTour();
     *     db.rebuildPathIndex();
     *     db.computeAllSlacks();
     *     db.updateOriginalArea();
     *
     * ----------------------------
     */

    void finalizeAfterParsing() {
        computeClockArrival();
        buildEulerTour();
        rebuildPathIndex();
        computeAllSlacks();
        updateOriginalArea();
        clearTargets();
    }
};

} // namespace skew

#endif // DS_H

